#! /bin/usr/env python
while t>0:
    flag = True
    n = input()
    #print(n.find('.'))
    #print(n.count('.'))
    
    if n.find('.') == -1:
        flag = False
    elif n.count('.') > 1:
            flag = False

    else:
        
        

        if n[0] == '+' or n[0] == '-' or n[0] == '.':

            for i in range(1, len(n)):
                if 'a' <= n[i] <= 'z' or   'A' <= n[i] <='Z':
                    flag = False
                    break
                elif n[i] == '+' or n[i] == '-':
                    flag = False
                    break

                else:
                    flag = True
                    
        else:
            for i in range(len(n)):            
                if  'a' <= n[i] <='z' or 'A' <= n[i] <='Z':
                    flag = False
                    break
                elif n[i] == '+' or n[i] == '-':
                    flag = False
                    break
    
                else:
                    flag = True

    if flag == False:
        print("False")
    else:
        print("True")

         
    t = t-1
