#! /bin/usr/env python
n = int(input())
#l = list(map(int, input().strip()))
#x = input()
#x = input()
#l = list(int, x.split())
l = [int(x) for x in input().split()]
   
m=[]
index = int(input())
for i in range(len(l)):
    m.append(0)
   
for i in range(len(l)):
    j = (i+2)%n
    m[j] = l[i]
#print(m)    
for i in range(len(m)):
    if m[i] == index:
        print(i)
        break
    else:
        continue
